fabricjs/fabricjs.com

test/functional/functional_tests.js

Better functional test page, 
SVGS are loaded as group and made wide as the image.
(Had to scale them, otherwise they are 100px width because of width 100%)

Fix functional test pages

---

posts/benchmarks/_posts/2011-9-1-raphael-vs-fabric-simple.html

The same problem with module as in last pr.

Fix bug with module function.

---

posts/benchmarks/_posts/2011-9-1-animation.html

There was not implementation for the fps counter.

Add fps counter.

---

posts/_posts/2012-8-12-fabric-intro-part-3.html
posts/benchmarks/_posts/2011-9-1-animation.html

There was not seeing text under the circle.

Fix the article.

---

js/kitchensink/controller.js

closes #86 
clear typo for overline

clear typo for overline

---

index.html
posts/_posts/2016-5-15-fabric-changelog.html
posts/demos/_posts/2011-9-1-kitchensink.html

Enabled mouswheel by default
removed jquery plugin to manage mousewheel, managed by canvas.on('mouse:wheel');
Added highlights

changes to website

---

posts/_posts/2012-6-25-fabric-intro-part-1.html

There was an apostrophe missing in one of the examples :)

Fix syntax error in introductory code example

---

docs/index.html

Bug fixed: Replaced incorrect href for Ellipse with correct one.

---

posts/demos/_posts/2014-10-16-video-element.html

using `getUserMedia` API to add webcam to HTML5 video demo

Adding webcam to video demo

---

posts/_posts/2017-08-17-v2-breaking-changes-2.html

Small typo in v2 breaking changes

---

build/index.html

blendimage_filter was not included in custom build

blendimage_filter added

---

posts/demos/_posts/2014-10-16-video-element.html

fixes https://github.com/fabricjs/fabric.js/issues/4989

Mute videos in example

---

posts/_posts/2018-2-10-using-transformations.html

This pr fixes #232 where several typos were found on the [Using Transformations](http://fabricjs.com/using-transformations) page. There are several grammatical changes included for easier reading.

Issue 232 - Fix typos and grammar on Using Transformations

---

posts/_posts/2017-06-18-changelog.html

fixed typo in new property name plus other tiny corrections.

corrected name of disableStyleCopyPaste property

---

posts/_posts/2012-8-12-fabric-intro-part-3.html

Fix [issue](https://github.com/fabricjs/fabric.js/issues/5776)

Changed value

---

posts/_posts/2017-06-17-fabric-intro-part-5.html

Sorry guys, my last PR was broken. Here's the fix.

fix: zoom was broken by PR256

---

posts/_posts/2012-6-25-fabric-intro-part-1.html

As raised in this issue https://github.com/fabricjs/fabric.js/issues/6100

Add missing single quote

---

build/index.html

Hello !
To fix this issue : https://stackoverflow.com/questions/64806064/fabric-js-4-2-control-does-not-show-when-select-object, I've added files on the build's files list

[FIX] build page for 4.2.0

---

posts/demos/_posts/2013-2-12-dynamic-patterns.html

There is an [issue](https://github.com/fabricjs/fabric.js/issues/6698) which I created a [pull request](https://github.com/fabricjs/fabric.js/pull/6701) for on Fabric.js. Discussing the solution with @asturur, he suggested we fix the demo, rather than reintroduce a [previously resolved issue](https://github.com/fabricjs/fabric.js/commit/c25116d3a82ddde1000c1245ffa6f94b8da03ed5#diff-12a4c03b64ef4498a7ff2de10d50ed27afd9f230a1fed7356b5211639724d7c3) to the codebase.
If the [formatting](https://prettier.io/) isn't desirable, I can remove it 🙂

Fix Dynamic Patterns Demo

---

js/kitchensink/controller.js
posts/demos/_posts/2011-9-1-kitchensink.html

1. Fixed Rasterize canvas buttons
2. Fixed Clip button
3. Added Clip Inverted button
4. Add strokeUniform checkbox
Used my own fork this time. Will open branch on official repo next time.

Misc kitchensink demo fixes

---

posts/demos/_posts/2020-06-20-build-minimap.md

Reworded phrase so it's gramatically correct. Also fixed typo, 'to' should actually be 'two'.

Fix typo and reword in minimap demo

---

posts/demos/_posts/2020-01-15-custom-controls-polygon.md

@asturur, I've made a number of changes to the wording of the Custom Controls demo description. Would you mind checking it over and making sure none of it has lost its meaning?

Reworded custom controls demo description

---

posts/_posts/2012-8-12-fabric-intro-part-3.html

Add link to the bottom of part 3 to match the previous parts of the introduction.

Add: link to part 3 for Part 4

---

posts/demos/_posts/2021-05-28-erasing.md

docs PR for https://github.com/fabricjs/fabric.js/pull/7289

docs(Erasing)

---

posts/demos/_posts/2018-2-18-events.html

Update `2018-2-18-events.html`
https://github.com/fabricjs/fabric.js/pull/7442

docs(): `drop:before` event

---

css/master.css
team/index.html

- Align GitHub button
- Add `alt` attributes in Team page
- Change `http://` to `https://`
Before:
After:

Polishing Github button and Team page

---

css/master.css
index.html

doc(version): automated version + latest cdn

---

test/lib/qunit.css
test/lib/qunit.js

feat(tests): make tests collapsing

---

articles/index.html
posts/_posts/2012-12-21-fabric-intro-part-4.html
posts/_posts/2016-11-26-fabric-object-caching.html
posts/_posts/2018-3-3-subclassing-tutorial.html

Misc spelling corrections submitted by [akaAbdullahMateen](https://github.com/akaAbdullahMateen) - https://github.com/fabricjs/fabric.js/issues/7748

docs() misc spelling corrections

---

posts/benchmarks/_posts/2013-7-27-group-performance.html

update to use new group v6 https://github.com/fabricjs/fabric.js/pull/7669

group-performance
